name: chatwiththeo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  device_preview: ^1.2.0
  another_flutter_splash_screen: ^1.2.1
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.14
  card_swiper: ^3.0.1
  go_router: ^14.6.0
  dots_indicator: ^2.1.1
  get_storage: ^2.1.1
  board_datetime_picker: ^2.1.6
  timeago: ^3.7.0
  toastification: ^2.3.0
  hl_image_picker: ^1.2.16
  
  flutter:
    sdk: flutter
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  icons_launcher: ^3.0.0

flutter:
  assets:
    - assets/
    - assets/bg/
    - assets/cover/
    - assets/icon/

  #   - images/a_dot_ham.jpeg
  uses-material-design: true

icons_launcher:
  image_path: "assets/logoapp.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true